### ISSUE TITLE
bitlbee support

### ISSUE THREAD

**Issue by terminaldweller** [hoehermann/purple-presage#1]
when i try to run purple-presage using bitlbee I get:

```
Warning: Can't find function `init_plugin_info' in `/usr/lib/bitlbee/libpresage.so'
Warning: Can't find function `init_plugin' in `/usr/lib/bitlbee/libpresage.so'
```

Does purple-presage support bitlbee? If yes, then what I am doing wrong?

**Comment by hoehermann** [comment]
Thank you for your request. I try to make this plug-in as compatible as I can, but I do not use bitlbee (or Spectrum) myself. I need to rely on community feed-back. This plug-in uses the same template as my other plug-ins (purple-gowhatsapp and purple-signald) and they have been reported to work. The functions `init_plugin` and `init_plugin_info` are not mandated by libpurple. bitlbee should be able to use the plug-in even without them. Maybe @mverboom @mooomooo @demure @Strykar or @yourealwaysbe can help us out.

If you want a feature-complete and reliable protocol bridge to Signal, but are not bound bitlbee, you may want to check out sildge https://git.sr.ht/~nicoco/slidgnal or matrix https://github.com/mautrix/signal.

**Comment by terminaldweller** [comment]
I am very familiar with your other projects. :D 
Thanks for being so awesome.

I ended up setting up mautrix-signal.
Thanks again.

If I figured out why I couldn't get bitlbee to work I'll reopen this.

**Comment by quotuva** [comment]
Just wanna chime in that I have it working on the latest Ubuntu so:

- Added an account normally with `hehoe-presage`
- (Then simply turning it on got me something related to 'QR code' on the `bitlbee` debug logs, and failed to connect. So...)
- Copy the `presage` folder already set up with `pidgin`, to `bitlbee`'s
- Turn it on

**Comment by hoehermann** [comment]
I'll put "make login procedure more bitlbee-friendly" on the list of things to be done. Thank you for your contribution.

**Comment by hoehermann** [comment]
With commit 1128a84, the plug-in should now detect the UI features (or rather the absence thereof) and provide the QR code URI in form of a text message. I added related instructions to the README.

**Comment by quotuva** [comment]
It works. Thank you! Btw is the `<br>` relevant to IRC clients? It was
printed raw on mine (rcirc).

**Comment by hoehermann** [comment]
Pidgin wants HTML, so I need to turn newlines into <br> tags for messages being displayed properly. As far as I understood, XMPP relays (such as Spectrum) also want HTML. I want to check with the devs whether that means I must or must not set the flag `PURPLE_CONNECTION_HTML` for other hosts (e.g. bitlbee) to handle it reasonably.
