### ISSUE TITLE
Error HTTP 409 when 

### ISSUE THREAD

**Issue by seblemaguer** [hoehermann/purple-presage#2]
Hello,

sorry, I am a bit confused on how to add an account. I tried the following steps:
   1. Create a new Pidgin account > select Signal (presage) and add "TEST" as username (I don't know my UUID, and I don't really understand how to get it)
   2. scan the QR-code which popped up.

It fails with an error HTTP 409.

Did I missed any steps or am I doing something wrong?

Thanks

**Comment by hoehermann** [comment]
There are some changes to the linking procedure mentioned in https://github.com/whisperfish/presage/commit/e2392c4. In 1d8bbd4, I updated the back-end library presage to 6.1.2 accordingly. It works for me. Does it help for you, too?

**Comment by seblemaguer** [comment]
Yes that solves it, thanks a lot :)
