### ISSUE TITLE
Login error: Username for this account must be <SOME-UUID>

### ISSUE THREAD

**Issue by k4r4b3y** [hoehermann/purple-presage#4]
Hello.  I am on debian 12.  I have installed signald from https://signald.org/articles/install/debian/

I also have installed bitlbee-libpurple package from debian 12 stable repos: https://packages.debian.org/bookworm/bitlbee-libpurple

Then I have compiled purple-presage from its source code ran the command: `sudo cmake --install .`  which has moved the file to `/usr/lib/x86_64-linux-gnu/purple-2/libpresage.so`

Now, I use ERC irc client, and follow the guide here (I don't apply the docker part): https://willvaughn.org/articles/running-bitlbee-and-signald-with-docker/

I start ERC with: `(erc :server "localhost" :port 6667 :nick "k4r4b3y")` command inside emacs scratch buffer.  Then, I switch to `&bitlbee` buffer inside emacs and execute: `account add hehoe-presage <MY-SIGNAL-PHONE-NUMBER>`.  I get the following output: `<root> Account successfully added with tag hehoe-presage`

Then, I run the following command inside the same buffer: `account hehoe-presage on`.  This outputs the following:
```
<LogonQRCode> k4r4b3y: Convert the next line into a QR code and scan it with
	      your main
	      device:<br>sgnl://linkdevice?uuid=<SECRET-STUFF>
```
I copy the `sgnl://linkdevice?uuid=<SECRET-STUFF>` to a new terminal window and convert it to a qrcode using `qrencode -t ansiutf8 'sgnl://linkdevice?uuid=<SECRET-STUFF>'`.  I scan the QR-code that gets outputted to my terminal with my signal android.  It tells me "OK, complete linking on the other device".  I turn my attention to ERC client, and it outputs:
``` 
<root> hehoe-presage - Login error: Username for this account must be
       '<SOME-UUID>'.
<root> hehoe-presage - Logging in: Signing off..
```
---
What does this mean?  How can I solve this?

**Comment by hoehermann** [comment]
While I work towards supporting biltlbee, I do not actually use it myself and have no experience how to operate, configure or use it. So please bear with me if my advice is not correct.

Internally, Signal does not use phone numbers to identify your account, but the randomly generated UUID. Instead of `account add hehoe-presage <MY-SIGNAL-PHONE-NUMBER>`, you need to use `account add hehoe-presage <THE-UUID-SHOWN-IN-THE-ERROR-MESSAGE>`, then it should work.

**Comment by k4r4b3y** [comment]
Frustrating -- just as I sat down to try out your suggestion, I am now getting a different error code:
```
<root> hehoe-presage - Login error: run Err
       ProvisioningError(ServiceError(UnhandledResponseCode { http_code: 409
       }))
<root> hehoe-presage - Logging in: Signing off.. 
```

**Comment by hoehermann** [comment]
It is the only way I know to get the UUID.

The 429 error happens if you unsuccessfully try to link too often. Maybe bitlbee retries automatically. Best disable the connection and try again a day later.

Also, I updated the master branch to use the newest version of the back-end library presage. Maybe that helps, too.

**Comment by k4r4b3y** [comment]
I just pulled your newest commits to my local copy, and re-built `purple-presage`.  After entering the usual commands in &bitlbee channel as shown below:

```
account add hehoe-presage <YOUR-SIGNAL-PHONE-NUMBER-HERE>
<root> Account successfully added with tag hehoe-presage
account hehoe-presage on
```

I get the HTTP 409 error:

```
<root> hehoe-presage - Login error: run Err
       ProvisioningError(ServiceError(UnhandledResponseCode { http_code: 409
       }))
<root> hehoe-presage - Logging in: Signing off..
```

**Comment by hoehermann** [comment]
All I can say, "works for me" (with Pidgin on Linux).

Can you install Pidgin and try the plug-in there?  
If it the same error is reported, then Signal does not like you in particular and I cannot do much about that.  
If it works with Pidgin but not in bitlbee, then it is a compatibility issue bitlbee which other bitlbee users might be able to help with.

**Comment by k4r4b3y** [comment]
I just installed `pidgin` package from debian bookworm repository.  I started pidgin, selected Signal (presage), and entered my signal account telephone number.  I am getting the following error message inside pidgin error, at the bottom of the pidgin window: 
```
<MY-SIGNAL-PHONE-NUMBER> disabled
Error linking device: Canceled
```
----
Maybe signal servers really doesn't like my account.

**Comment by hoehermann** [comment]
A couple of days after you opened this issue, the same problem was reported to [flare](https://gitlab.com/schmiddi-on-mobile/flare/-/issues/221) and ultimately [resolved upstream](https://github.com/whisperfish/presage/commit/464626aa27829bc4d641086359afccdb0da4711f) four days ago. Please feel free to try again with purple-presage's current master.

**Comment by k4r4b3y** [comment]
@hoehermann re-building and re-installing from the current master allowed me to link my signal account to hehoe-presage.  I have used `account add hehoe-presage <THE-UUID-SHOWN-IN-THE-ERROR-MESSAGE>`.  Thanks.
