### ISSUE TITLE
JSON error: missing field `expire_timer_version`

### ISSUE THREAD

**Issue by webmeister** [hoehermann/purple-presage#7]
I upgraded from 52aa0a0 to ad45f3f. Now when I send a message, my local Pidgin conversation displays "store error: JSON error: missing field `expire_timer_version` at line 1 column 367" instead of my message. Otherwise the message seems to be sent correctly. Downgrading solves the issue.

**Comment by hoehermann** [comment]
Thank you for the report. I encountered this issue, too. I think it was resolved by re-linking on the more recent version.

**Comment by webmeister** [comment]
What exactly did you do to solve the issue? I tried a clean build, but that did not change anything.

**Comment by hoehermann** [comment]
Unfortunately, I do not exactly remember what I did. It must have been something simple. Anything complicated I would have documented. ;) I guess I just removed the link in the phone's Signal app and then scanned the QR code again in Pidgin.

**Comment by webmeister** [comment]
I've got it working now, with c340ed0. For future reference, this is what I did:
1. Do a clean build of purple-presage. I had some files from an old build lying around, that apparently got reused, which caused a SIGILL somewhere in libpresage.so as soon as the presage account was activated.
2. Stop Pidgin, unlink the Pidgin device, delete ~/.purple/presage and restart Pidgin to relink the device.
